services:
  users:
    container_name: vibes-users
    build:
      context: ./packages/users
      dockerfile: Dockerfile
    env_file:
      - ./packages/users/.env
    ports:
      - '5000:5000'
    depends_on:
      migrations:
        condition: service_completed_successfully
      rabbitmq:
        condition: service_healthy
  
  notifications:
    container_name: vibes-notifications
    build:
      context: ./packages/notifications
      dockerfile: Dockerfile
    env_file:
      - ./packages/notifications/.env
    depends_on:
      rabbitmq:
        condition: service_healthy

  migrations:
    container_name: vibes-migrations
    build:
      context: ./packages/migrations
      dockerfile: Dockerfile
    depends_on:
      - postgres
    restart: "no"

  postgres:
    container_name: vibes-postgres
    image: postgres:latest
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASS}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    container_name: vibes-rabbitmq
    image: rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    ports:
      - 5672:5672

volumes:
  postgres_data: {}